[package]
name = "fox_game"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
clap_derive = "4.5.13"
num-format = {version = "0.4.4", features = ["with-system-locale"]}
num_cpus = "1.16.0"
rand = "0.8.5"
random = "0.14.0"
rayon = "1.10.0"

